version: '3'
services:
  react-app:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - build:/app/build

  nginx:
    image: nginx:alpine
    ports:
      - 784:80
    volumes:
      - build:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services.json:/conf/services.json # replace with /path/to/services.json

volumes:
  build:
    driver: local